### ISSUE TITLE
Bug: Volume down single press mutes iPad

### ISSUE THREAD

**Issue by jessthecatmeow** [rpetrich/libactivator#129]
Hello again! I had this very same issue a while ago. On my iPad1 3G fw 5.0, when I (single, no hold) press the down volume button, it mutes my iPad. I reset the settings from within the Activator app with no luck. Thanks for such a great tweak! This is by far the number one reason why I Jailbreak, I even wrote a piece for LifeHacker about it :-)

**Comment by moogagot** [comment]
I have the same problem.  After a free reboot, the first two volume downs work, but the third and onward force a mute.  Resetting activator does not work.  There is no problem in safe mode.  I am currently running iOS 4.2.1.

This is a major issue.  Please fix!

**Comment by chbisio** [comment]
Noticed this after the last update, hoping it gets fixed soon.

**Comment by Lunat1k** [comment]
1.8.6 Beta 2 fixed this issue

**Comment by moogagot** [comment]
Thanks for the fix!

**Comment by chbisio** [comment]
Yes thanks for the fix, BUT now the behaviour for full press to mute completely is gone!
You have to keep pressing until it goes all the way down... what a complicated issue!

**Comment by Lunat1k** [comment]
He also needs to add Mute as an action so we can also assign it to other triggers.

**Comment by chbisio** [comment]
I posted about the bug and he said explicitly that it won´t be fixed... it's a shame because
we lose a basic iOS functionality...see here:
https://github.com/rpetrich/libactivator/issues/132#issuecomment-2735386

**Comment by Lunat1k** [comment]
Well that's pretty crappy of him to take away built in functionality. Like I said he should least add a Mute action so that we can reassign it to the short hold trigger.

**Comment by chbisio** [comment]
Well let's not be aggresive, he already develops a great utility, who knows maybe that day he was in a bad mood or something... at least we got the bug fixed!

**Comment by Lunat1k** [comment]
I'm not being aggressive. I'm just pointing out that the point of jailbreaking and using these kinds of utilities are supposed to enhance the user experience. Not take away from.

**Comment by chbisio** [comment]
Completely agree with you... just said that in case of the developer was reading this...

**Comment by jessthecatmeow** [comment]
As of 1.5.8, this issue has been fixed

**Comment by chbisio** [comment]
Yes, this issue is fixed but a new one has arisen as I mentioned before, now the standard iOS functionality of keep pressing the down volume button a couple of seconds to mute the devices is not working in the latest version of activator.

**Comment by chbisio** [comment]
The issue is back in the latest beta as of today December 29th, 2011.

**Comment by Wanny** [comment]
This issue still happens as of today February 10th, 2013.
